apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devopsapp
  template:
    metadata:
      labels:
        app: devopsapp
    spec:
      containers:
        - name: devopsapp
          image: ghcr.io/gowrishankar330/devops-50-assignments/devopsapp:8f13f1e82d4ea3289d666967db9c5481d8b399e8
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 2
