apiVersion: v1
kind: Service
metadata:
  name: dataapp
  namespace: team-payments
  labels:
    app: dataapp
spec:
  selector:
    app: dataapp
  ports:
    - name: http
      port: 80
      targetPort: 8080